# Generated by Django 3.2 on 2022-01-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceing',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
