# Generated by Django 3.2 on 2022-01-18 10:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0002_priceing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceing',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='sevice details'),
        ),
    ]
