# Generated by Django 3.2 on 2021-12-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_rename_title_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
