# Generated by Django 3.2 on 2022-01-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_auto_20220103_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='header_txt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='long_txt',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
