# Generated by Django 3.2 on 2022-01-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
